# syntax=ghcr.io/azure/dalec/frontend:0.17

args:
    VERSION: 1.34.1
    COMMIT: 93248f9ae092f571eb870b7664c534bfc7d00f03
    REVISION: 1
name: kube-apiserver
packager: Azure Container Upstream
vendor: Microsoft Corporation
license: Apache-2.0
website: https://github.com/kubernetes/kubernetes
description: Kubernetes API Server
x-build-extensions:
    image-name: kube-apiserver
version: ${VERSION}
revision: ${REVISION}
sources:
    kubernetes:
        generate:
            - gomod: {}
        git:
            url: https://github.com/kubernetes/kubernetes.git
            commit: ${COMMIT}
            keepGitDir: true
conflicts:
    kubernetes-kube-apiserver:
targets:
    azlinux3:
        dependencies:
            build:
                msft-golang:
                git:
                make:
                gcc:
                sed:
                rsync:
            runtime:
                openssl-libs:
                kubernetes-gorunner:
                    version:
                        - "== 0.17.8"
            extra_repos:
                - config:
                    azl-cloud-native.repo:
                        inline:
                            file:
                                contents: |
                                    [azlinux-cloud-native]
                                    name=Azure Linux Cloud Native $releasever $basearch
                                    baseurl=https://packages.microsoft.com/azurelinux/$releasever/prod/cloud-native/$basearch
                                    gpgkey=file:///etc/pki/rpm-gpg/MICROSOFT-RPM-GPG-KEY
                                    gpgcheck=1
                                    repo_gpgcheck=1
                                    enabled=1
                                    skip_if_unavailable=True
                                    sslverify=1
                  envs:
                    # The repository will only be available when installing into the final container
                    - install
build:
    env:
        VERSION: "v${VERSION}"
        COMMIT: "${COMMIT}"
        GOPROXY: direct
        GOEXPERIMENT: systemcrypto
        CGO_ENABLED: "1"
        FORCE_HOST_GO: true
        KUBE_GIT_TREE_STATE: clean
    steps:
        - command: |
            cd kubernetes
            major="$(echo ${VERSION} | grep -Po "(?<=v)[0-9]+")"
            minor="$(echo ${VERSION} | grep -Po "(?<=v${major}.)[0-9]+")"
            SANITIZED_VERSION=$(printf '%s' "$VERSION" | sed 's/~/-/g')
            cat <<EOF >version-file
            KUBE_GIT_COMMIT='${COMMIT}'
            KUBE_GIT_TREE_STATE='clean'
            KUBE_GIT_VERSION='${SANITIZED_VERSION}'
            KUBE_GIT_MAJOR='${major}'
            KUBE_GIT_MINOR='${minor}'
            EOF
            KUBE_VERBOSE=3 KUBE_GIT_VERSION_FILE=version-file  WHAT=cmd/kube-apiserver KUBE_CGO_OVERRIDES=kube-apiserver DBG=1 make
            setcap cap_net_bind_service=+ep _output/bin/kube-apiserver
artifacts:
    binaries:
        kubernetes/_output/bin/kube-apiserver: {}
    licenses:
        kubernetes/LICENSE: {}
tests:
    - name: Check files
      files:
        /usr/bin/kube-apiserver:
            permissions: 0755
image:
    entrypoint: /usr/bin/go-runner
