# File: 1es-pipeline.yml
name: 1ES-Build-on-Merge
trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
    - repository: self
      type: github
      name: jeremyrickard/ado-pipeline-test

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: staging-pool-amd64-mariner-2
      image: azcu-1es-agent-amd64-mariner-2-img
      os: linux
    sdl:
      sourceAnalysisPool:
        name: staging-pool-amd64-mariner-2
        # The image must be windows-based due to restrictions of the SDL tools. See: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sdlanalysis/overview#how-to-specify-a-windows-pool-for-the-sdl-source-analysis-stage
        # In the case of a windows build, this can be the same as the above pool image.
        image: azcu-agent-amd64-windows-22-img
        os: windows
      sourceRepositoriesToScan:
        include:
        - repository: self
    stages:
      - stage: Build
        jobs:
          - job: PrintDeletedFiles
            steps:
              - checkout: self
                persistCredentials: true
              # Print deleted files from triggering commit
              - script: |
                  set -euo pipefail
                  SHA="$(Build.SourceVersion)"
                  echo "Checking for deleted files in commit $SHA..."
                  DELETED_FILES=$(git diff --diff-filter=D --name-only "${SHA}^1" "${SHA}")
                  if [ -z "$DELETED_FILES" ]; then
                    echo "No files were deleted in this commit."
                  else
                    echo "Deleted files:"
                    echo "$DELETED_FILES"
                  fi
                displayName: 'Print deleted files'